### PR TITLE
Fix helm chart labels

### PR DESCRIPTION
**Pull request by hkroger**
Fix problems related to #17.

Removed 'crd-install' hook because CRDs are installed anyways before other components. See: https://stackoverflow.com/questions/51957676/helm-install-in-certain-order

'crd-install' causes CRD not to be uninstalled by default when release is deleted.

What do you think?

### CODE REVIEW

**Comment by allamand** [comment]
Hello @hkroger,

thanks for contributing this is awsome :)

Concerning the crd-install If you remove it, then the helm won't install it and the operator wont works.
In fact this is needed to be installed through helm in order to pass the automatic tests on charts/helm : https://github.com/helm/charts/pull/14414

Also the fact that if we delete the Helm, the CRD is not deleted is actually a "feature" because if we delete the CRD, then all associated ressources (cassandra clusters) are also deleted and this is not what we wanted in the first place.

**Comment by allamand** [comment]
For the rest I agree but for reinstall the crd with helm you can disable the hook with --no-hooks cf https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/master/helm/cassandra-operator/readme.md#install-of-the-crd.

Can you resend the PR without removing the crd-hook ?

thanks

**Comment by hkroger** [comment]
@allamand, alright if you prefer it this way. Not a problem for me :) I pushed an updated version.

**Comment by allamand** [comment]
@hkroger thanks a lot for you're contribution. I'll merge it now :)

**Pull request merged**
