### PR TITLE
[WIP] initial schema after running `operator-sdk generate openapi`

### PR DESCRIPTION
**Pull request by jsanda**
This PR is for #34. 

**Note:** This is a WIP and not ready to be merged.

I am opening the PR so I can gather feedback as I make changes.

### CODE REVIEW

**Comment by allamand** [comment]
Thanks John, all description here are automatically generated ? Or did you update them ?

**Comment by jsanda** [comment]
Descriptions are automatically generated. I think that `operator-sdk generate openapi` delegates most of the work to [kube-openapi](https://github.com/kubernetes/kube-openapi). I am still trying to understand how things work. The docs in operator-sdk are really lacking for the `generate openapi` command. The docs for `kube-openapi` aren't a whole lot better.

I will need to update `Makefile` to call `operator-sdk generate openapi`.

I will also need to make some changes in `cassandracluster_types.go`. If you look in the crd.yaml file with my initial commit, you will see that baseImage is a required property; however, it is not actually a required property. Adding the `omitempty` option will produce a schema without `baseImage` being required.

**Comment by jsanda** [comment]
I have made some progress but I still have not figured out how to specify constraint likes min, max, or patterns. I do not think we want to add constraints directly to the crd.yaml file because the changes will be overwriten and lost the next time `operator-sdk generate openapi` is run.

**Comment by jsanda** [comment]
This PR fell off my radar. I will try to revisit over the next couple days. I think I experimented with those changes before I was aware of the validation annotations. The best and only reference I could find for them is at https://book.kubebuilder.io/reference/markers/crd-validation.html.

**Comment by cscetbon** [comment]
@jsanda, any time soon to spend on it ?

**Comment by jsanda** [comment]
@cscetbon My apologies for the delay. I am going to work on it tonight which is UTC-04:00.

**Comment by jsanda** [comment]
I am closing this and will open a new PR.

**Pull request closed without merging**
